namespace PhasmoSheet.Core.Common
{
    public enum GhostEvents
    {
        GhostTurnedOffBreaker,
        GhostTurnedOnBreaker,
        GhostTurnedOnLightSwitch,
        AirballEvent,
        GhostShowedFootprints,
        GhostIsVisibleInPhoto,
        HuntedInSameRoomAsPlayer,
        HuntedWithin3mOfLitCandle,
        HuntedWithin5mOfCrucifix,
        LeftRoomWithin90sOfSmudge,
        EMFAtBreakerWithoutTurningOnOrOff,
        InteractingWith2ThingsInSeparateRoomsWithinSplitSecond,
        HuntingUponBlowingCandle,
        TeleportingToPlayer,
        ShowingBreathDuringHunt,
        DisappearedDuringPhoto,
        Showing6FingeredHand,
        ThrowingObjectsFar,
        ThrowingMultipleObjectsAtOnce,
        ExclusiveScreamInParamic,
        ClosingADoorQuickly,
        ShowingUpAsShadowInSummoningCircle,
        TurnsOffBreakerFrequently,
        FavoriteRoomChanged,
        BreathingHeavilyAsSpiritBoxResponse,
    }
}
